author: DerFlash
database: false
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: me.derflash.plugins.villagerspecialperms.VillagerSpecialPerms
name: VillagerSpecialPerms
startup: postworld
url: http://www.cube-nation.de/
version: '1.0'
